version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sami_nodejs
      POSTGRES_PASSWORD: "nodejs123"
      POSTGRES_DB: API_express_nodejs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: